Update compile_meteor

diff --git a/bin/compile_meteor b/bin/compile_meteor
--- a/bin/compile_meteor
+++ b/bin/compile_meteor
@@ -52,7 +52,7 @@ build() {
     head "Building Meteor App Bundle"
     cd $APP_SOURCE
     # can't build with these platforms enabled, it looks like
-    set +e  # these next few are allowed to exit nonzero
+    #set +e  # these next few are allowed to exit nonzero
     #grep -Fxq ios .meteor/platforms
     #if [ $? -eq 0 ]; then
      # meteor remove-platform ios 2>&1 | indent
@@ -61,7 +61,7 @@ build() {
     #if [ $? -eq 0 ]; then
      # meteor remove-platform android 2>&1 | indent
     #fi
-    set -e  # back to failing if any command fails
+    #set -e  # back to failing if any command fails
     meteor build ../build --directory 2>&1 | indent
     head "Installing App's NPM Dependencies"
     (cd ../build/bundle/programs/server && npm install 2>&1 | indent)
